"""
BrandCraft Export API Router
Handles PDF generation for brand guides.
"""

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
import datetime

router = APIRouter(prefix="/export", tags=["Export"])


class BrandGuideRequest(BaseModel):
    """Data for brand guide PDF."""
    brand_name: str
    tagline: Optional[str] = None
    industry: Optional[str] = None
    description: Optional[str] = None
    brand_voice: Optional[dict] = None
    primary_color: Optional[str] = None
    secondary_color: Optional[str] = None
    font_primary: Optional[str] = None
    font_secondary: Optional[str] = None


@router.post("/brand-bible")
async def generate_brand_bible(data: BrandGuideRequest):
    """Generate a PDF brand guide."""
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, 
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=28,
        spaceAfter=30,
        textColor=colors.HexColor('#667eea')
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        spaceAfter=12,
        textColor=colors.HexColor('#333333')
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=8,
        leading=16
    )
    
    story = []
    
    # Title
    story.append(Paragraph(f"{data.brand_name} Brand Guide", title_style))
    story.append(Paragraph(f"Generated by BrandCraft • {datetime.date.today().strftime('%B %Y')}", 
                           styles['Italic']))
    story.append(Spacer(1, 30))
    
    # Tagline
    if data.tagline:
        story.append(Paragraph("Tagline", heading_style))
        story.append(Paragraph(f'"{data.tagline}"', body_style))
        story.append(Spacer(1, 20))
    
    # About
    if data.description:
        story.append(Paragraph("Brand Description", heading_style))
        story.append(Paragraph(data.description, body_style))
        story.append(Spacer(1, 20))
    
    # Industry
    if data.industry:
        story.append(Paragraph("Industry", heading_style))
        story.append(Paragraph(data.industry.title(), body_style))
        story.append(Spacer(1, 20))
    
    # Brand Voice
    if data.brand_voice:
        story.append(Paragraph("Brand Voice DNA", heading_style))
        voice_data = [
            ["Personality", data.brand_voice.get('personality', 'Not specified')],
            ["Tone", data.brand_voice.get('tone', 'Not specified')],
            ["Target Audience", data.brand_voice.get('target_audience', 'Not specified')],
        ]
        voice_table = Table(voice_data, colWidths=[2*inch, 4*inch])
        voice_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f8f9fa')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#333333')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ]))
        story.append(voice_table)
        story.append(Spacer(1, 20))
    
    # Colors
    if data.primary_color or data.secondary_color:
        story.append(Paragraph("Color Palette", heading_style))
        colors_text = []
        if data.primary_color:
            colors_text.append(f"Primary: {data.primary_color}")
        if data.secondary_color:
            colors_text.append(f"Secondary: {data.secondary_color}")
        story.append(Paragraph(" | ".join(colors_text), body_style))
        story.append(Spacer(1, 20))
    
    # Typography
    if data.font_primary or data.font_secondary:
        story.append(Paragraph("Typography", heading_style))
        if data.font_primary:
            story.append(Paragraph(f"Primary Font: {data.font_primary}", body_style))
        if data.font_secondary:
            story.append(Paragraph(f"Secondary Font: {data.font_secondary}", body_style))
        story.append(Spacer(1, 20))
    
    # Footer
    story.append(Spacer(1, 40))
    story.append(Paragraph("—", styles['Normal']))
    story.append(Paragraph("This brand guide was generated using BrandCraft AI Branding Suite.", 
                           styles['Italic']))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    
    filename = f"{data.brand_name.replace(' ', '_')}_Brand_Guide.pdf"
    
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
